"""test 3

Revision ID: 437f3b8493c0
Revises: d8c75545dd40
Create Date: 2022-11-07 23:11:00.105849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437f3b8493c0'
down_revision = 'd8c75545dd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('mimetype', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'product', ['img'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'mimetype')
    # ### end Alembic commands ###
