"""test

Revision ID: d8c75545dd40
Revises: 8a25b30a6ca2
Create Date: 2022-11-07 23:09:33.737277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c75545dd40'
down_revision = '8a25b30a6ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_name', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('mimetype', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'product', ['img'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'mimetype')
    op.drop_column('product', 'img_name')
    # ### end Alembic commands ###
